baseurl = "/"
languageCode = "en-us"
title = "MVPS"
publishDir = "docs"

[params]
  description = "best burgers in the world"

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 1
[[menu.main]]
    name = "Drinks"
    url  = "/drinks"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 3
[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 4
[[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 5
